version: "3.8"
services:
  starter:
    container_name: "${PROJECT_NAME}_nextjs"
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
